"""parlando menu bar app.

Runs the dictation engine in the background; the menu bar offers start/stop,
language switching, Enter mode and quit. No terminal window needed.

Usage:
    parlando                   # start in the menu bar (the default of `parlando`)
    parlando --install-app     # create ~/Applications/Parlando.app (recommended)
    parlando --uninstall-app
    parlando --install-login   # auto-start at login (opens Parlando.app)
    parlando --uninstall-login
    parlando-menubar           # same app; kept as an alias

Why an app bundle: macOS ties Microphone and Accessibility permissions to
the *responsible* application. Run from a terminal, that is Terminal/iTerm/
VS Code, which is confusing and breaks whenever you switch terminals.
`--install-app` writes a thin bundle (Info.plist, icon, a prebuilt Mach-O
stub and a launch script) that runs this package's Python; launched from
Finder, Spotlight or the LaunchAgent, permissions are then requested and
stored as "Parlando".

Menu bar icon (template, adapts to light/dark): three-bar waveform = ready,
waveform with a dot = recording, two equal bars = paused. A small badge
next to it shows a non-default language (ᵉⁿ / ᵗʳ), model download
progress, or a problem (!). The menu opens with a status block (what
parlando is doing, a hint, and a one-click fix when a permission is
missing). The global hotkey works too (default: single tap of right
Option).
"""

from __future__ import annotations

import asyncio
import os
import plistlib
import shutil
import subprocess
import sys
import threading
from pathlib import Path

from parlando import engine

BUNDLE_ID = "com.parlando.menubar"
APP_BUNDLE = Path.home() / "Applications" / "Parlando.app"
LAUNCH_AGENT = Path.home() / "Library" / "LaunchAgents" / f"{BUNDLE_ID}.plist"
APP_LOG = Path.home() / "Library" / "Logs" / "parlando-app.log"

LANGUAGES = {
    "Türkçe": "Turkish",
    "English": "English",
}
# Superscript badge shown next to the icon when the language is not the
# default (Config.language).
LANGUAGE_BADGES = {"Turkish": "ᵗʳ", "English": "ᵉⁿ"}

# Template icons (black + alpha): macOS recolors them to match the menu bar
# in light and dark mode. Regenerate with scripts/make_icons.py.
_ASSETS = Path(__file__).resolve().parent / "assets"
ICONS = {
    "idle": str(_ASSETS / "mic.png"),
    "recording": str(_ASSETS / "mic-recording.png"),
    "paused": str(_ASSETS / "mic-paused.png"),
}
APP_ICNS = _ASSETS / "Parlando.icns"
# Prebuilt Mach-O stub (scripts/launcher.c): macOS will not launch a bundle
# whose main executable is a script, so this binary runs launch.sh as a
# child and waits (see launcher.c for why not exec).
APP_LAUNCHER_BIN = _ASSETS / "parlando-launcher"


# -----------------------------------------------------------------------------
# App bundle (~/Applications/Parlando.app)
# -----------------------------------------------------------------------------

# launch.sh execs the interpreter that owns this package: an absolute path
# (uv tool or a venv, for --install-app) or a path relative to
# Contents/Resources (the embedded runtime of a distributable build made by
# scripts/build_app.sh). Using `python -m` rather than the console script
# keeps it valid across reinstalls. stdout/stderr go to a log: there is no
# terminal.
_LAUNCH_SH = """#!/bin/sh
# Parlando.app launch script, generated by parlando ({origin}).
RES=$(cd "$(dirname "$0")" && pwd)
PARLANDO_APP_BUNDLE=$(cd "$RES/../.." && pwd); export PARLANDO_APP_BUNDLE
exec {python} -m parlando.menubar "$@" >>"$HOME/Library/Logs/parlando-app.log" 2>&1
"""


def bundle_plist(version: str = "1.0") -> dict:
    # --install-app deliberately passes no package version: that bundle is
    # only a launcher, and ad-hoc signed bundles are identified by content
    # hash in the privacy database, so a stable bundle keeps granted
    # permissions valid across `uv tool upgrade parlando`. Distributable
    # builds (scripts/build_app.sh) carry the real version: every release
    # is a new bundle anyway.
    return {
        "CFBundleName": "Parlando",
        "CFBundleDisplayName": "Parlando",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": "parlando",
        "CFBundleIconFile": "Parlando",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": version,
        "CFBundleVersion": version,
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "13.0",
        "LSUIElement": True,  # menu bar only: no Dock icon, no app switcher
        "NSHighResolutionCapable": True,
        "NSHumanReadableCopyright": "MIT License",
        "NSMicrophoneUsageDescription": (
            "Parlando listens to your voice to type what you say. "
            "Audio never leaves this Mac."
        ),
    }


def build_app_bundle(
    dest: Path,
    python: str | None = None,
    sign: bool = True,
    version: str = "1.0",
) -> Path:
    """Write a minimal .app at `dest` (replacing any existing one).

    `python`: absolute interpreter path, or a path relative to
    Contents/Resources for a runtime embedded in the bundle.
    """
    python = python or sys.executable
    if Path(python).is_absolute():
        py_expr, origin = _sh_quote(python), "--install-app"
    else:
        py_expr, origin = '"$RES"/' + _sh_quote(python), "scripts/build_app.sh"
    contents = dest / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    if dest.exists():
        shutil.rmtree(dest)
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    with open(contents / "Info.plist", "wb") as fh:
        plistlib.dump(bundle_plist(version), fh)
    exe = macos / "parlando"
    shutil.copyfile(APP_LAUNCHER_BIN, exe)
    exe.chmod(0o755)
    script = resources / "launch.sh"
    script.write_text(_LAUNCH_SH.format(python=py_expr, origin=origin))
    script.chmod(0o755)
    shutil.copyfile(APP_ICNS, resources / "Parlando.icns")

    if sign:
        # Ad-hoc signature: no certificate needed. It gives the bundle a
        # stable identity for the privacy (TCC) database.
        subprocess.run(
            ["codesign", "--force", "--deep", "--sign", "-",
             "--identifier", BUNDLE_ID, str(dest)],
            check=True,
            capture_output=True,
        )
    return dest


def _sh_quote(path: str) -> str:
    return "'" + path.replace("'", "'\\''") + "'"


_LSREGISTER = (
    "/System/Library/Frameworks/CoreServices.framework/Frameworks/"
    "LaunchServices.framework/Support/lsregister"
)


def install_app() -> int:
    build_app_bundle(APP_BUNDLE)
    # Register with LaunchServices so Spotlight/Finder show the name and
    # icon immediately instead of after the next indexing pass.
    if os.path.exists(_LSREGISTER):
        subprocess.run([_LSREGISTER, "-f", str(APP_BUNDLE)], check=False, capture_output=True)
    print(
        f"Installed: {APP_BUNDLE}\n"
        "Open it from Finder or Spotlight (\"Parlando\"). macOS will ask for "
        "Microphone and Accessibility permissions in the name of Parlando; "
        "grant both; Parlando picks them up without a restart.\n"
        f"App output goes to {APP_LOG}"
    )
    return 0


def uninstall_app() -> int:
    if LAUNCH_AGENT.exists():
        uninstall_login()
    if APP_BUNDLE.exists():
        shutil.rmtree(APP_BUNDLE)
        print(f"Removed {APP_BUNDLE}")
    else:
        print("Not installed.")
    return 0


# -----------------------------------------------------------------------------
# Start at login (LaunchAgent)
# -----------------------------------------------------------------------------


def install_login() -> int:
    # Launch through the app bundle so permissions belong to "Parlando",
    # not to a bare python binary. Build it only if missing: rewriting a
    # bundle changes its hash and would invalidate granted permissions.
    if not APP_BUNDLE.exists():
        build_app_bundle(APP_BUNDLE)
        print(f"Created {APP_BUNDLE}")
    plist = {
        "Label": BUNDLE_ID,
        "ProgramArguments": ["/usr/bin/open", "-g", str(APP_BUNDLE)],
        "RunAtLoad": True,
        "KeepAlive": False,
        "StandardErrorPath": str(Path.home() / "Library/Logs/parlando-agent.log"),
    }
    LAUNCH_AGENT.parent.mkdir(parents=True, exist_ok=True)
    with open(LAUNCH_AGENT, "wb") as fh:
        plistlib.dump(plist, fh)
    subprocess.run(["launchctl", "unload", str(LAUNCH_AGENT)], capture_output=True)
    subprocess.run(["launchctl", "load", str(LAUNCH_AGENT)], check=False)
    print(f"Installed: {LAUNCH_AGENT}\nparlando will start at your next login.")
    return 0


def uninstall_login() -> int:
    subprocess.run(["launchctl", "unload", str(LAUNCH_AGENT)], capture_output=True)
    if LAUNCH_AGENT.exists():
        LAUNCH_AGENT.unlink()
        print("Uninstalled.")
    else:
        print("Not installed.")
    return 0


# -----------------------------------------------------------------------------
# Relaunch guard: survive the kill macOS does when Accessibility is toggled
# -----------------------------------------------------------------------------

GUARD_LABEL = "com.parlando.relaunch-guard"
GUARD_PLIST = Path.home() / "Library" / "Application Support" / "parlando" / "relaunch-guard.plist"


def app_bundle_path() -> Path | None:
    """The .app we run from (launch.sh exports it), or None from a terminal."""
    p = os.environ.get("PARLANDO_APP_BUNDLE")
    return Path(p) if p and p.endswith(".app") else None


def guard_plist(label: str, pid: int, app: Path) -> dict:
    # launchd runs this outside the app's process group, so it survives
    # when macOS terminates the app on the Accessibility switch. It waits
    # for the app to be gone and opens it again (LaunchServices launch, so
    # permissions still belong to Parlando).
    script = (
        f"while kill -0 {pid} 2>/dev/null; do sleep 0.5; done; sleep 1; "
        f"/usr/bin/open -g {_sh_quote(str(app))}"
    )
    return {
        "Label": label,
        "ProgramArguments": ["/bin/sh", "-c", script],
        "RunAtLoad": True,
        "KeepAlive": False,
    }


class RelaunchGuard:
    """Registers/removes the launchd job around the permission grant.

    Active only while the Accessibility problem is showing. Stopped when
    the permission arrives (the app keeps running) and on a normal quit
    (so quitting never respawns the app). If macOS kills the app instead,
    the guard fires and the app comes back already trusted.
    """

    def __init__(self, app: Path | None) -> None:
        self.app = app
        self.active = False

    def _domain(self) -> str:
        return f"gui/{os.getuid()}"

    def start(self) -> None:
        if self.active or self.app is None:
            return
        GUARD_PLIST.parent.mkdir(parents=True, exist_ok=True)
        with open(GUARD_PLIST, "wb") as fh:
            plistlib.dump(guard_plist(GUARD_LABEL, os.getpid(), self.app), fh)
        subprocess.run(["launchctl", "bootout", f"{self._domain()}/{GUARD_LABEL}"],
                       capture_output=True)
        r = subprocess.run(["launchctl", "bootstrap", self._domain(), str(GUARD_PLIST)],
                           capture_output=True, text=True)
        self.active = r.returncode == 0
        if self.active:
            engine.LOGGER.info("relaunch guard armed (pid %d)", os.getpid())
        else:
            engine.LOGGER.warning("relaunch guard failed: %s", r.stderr.strip())

    def stop(self) -> None:
        if not self.active:
            return
        self.cleanup()
        self.active = False
        engine.LOGGER.info("relaunch guard disarmed")

    def cleanup(self) -> None:
        """Remove a finished or stale job (e.g. the one that relaunched us)."""
        subprocess.run(["launchctl", "bootout", f"{self._domain()}/{GUARD_LABEL}"],
                       capture_output=True)


# -----------------------------------------------------------------------------
# Status presentation
# -----------------------------------------------------------------------------

SETTINGS_PANES = {
    "accessibility": "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility",
    "microphone": "x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone",
}

_PROBLEM_TEXT = {
    "accessibility": (
        "Accessibility permission needed",
        "Hotkey and typing are off until Parlando is allowed; "
        "it reopens by itself if macOS quits it when you flip the switch",
        "Open Accessibility settings…",
    ),
    "microphone": (
        "Microphone is silent",
        "Allow Parlando under Microphone; it recovers by itself",
        "Open Microphone settings…",
    ),
}


def _tap_key(eng) -> str:
    """'right ⌥ Option' or the raw combo; '' when there is no hotkey."""
    key = eng.cfg.hotkey
    if not key:
        return ""
    return engine.TAP_KEY_LABELS.get(key, key)


def describe_status(eng) -> dict:
    """Turn engine state into what the menu shows.

    Returns: badge (text next to the icon), icon (idle/recording/paused),
    primary/secondary (the two status lines), action (problem key whose
    settings pane the third line opens, or None), toggle (title of the
    start/stop item), can_toggle.
    """
    st = eng.status
    lang = eng.cfg.language
    lang_badge = (
        "" if lang == engine.Config.language else LANGUAGE_BADGES.get(lang, "")
    )
    key = _tap_key(eng)
    tap = f"tap {key}" if key else "use the menu"
    words = f"{eng.total_words} words typed"
    asr = f" · ASR {eng.asr_ms:.0f} ms" if eng.asr_ms else ""
    out = dict(badge=lang_badge, icon="idle", action=None,
               toggle="Start recording", can_toggle=True)

    if st.phase == "downloading":
        pct = st.progress
        out.update(
            badge=f"{pct * 100:.0f}%" if pct is not None else "⬇",
            primary=("Downloading " + st.detail.split(" · ")[0]
                     + (f"… {pct * 100:.0f}%" if pct is not None else "…")),
            secondary=(f"{engine.human_bytes(st.downloaded)} of "
                       f"{engine.human_bytes(st.total)} · first run only"
                       if st.total else "First run only · this can take a few minutes"),
            toggle="Start recording", can_toggle=False,
        )
        return out
    if st.phase in ("starting", "loading"):
        out.update(
            badge="…",
            primary="Starting up…" if st.phase == "starting" else f"Loading {st.detail}…",
            secondary="Ready in a few seconds",
            can_toggle=False,
        )
        return out

    if st.problems:
        problem = st.problems[0]
        title, hint, _ = _PROBLEM_TEXT.get(problem, (problem, "", ""))
        out.update(badge="!", primary=f"⚠️ {title}", secondary=hint, action=problem)
        # The recording controls stay available (menu use works without
        # Accessibility; typing does not).
    elif st.phase == "recording":
        secs = eng.rec_samples / engine.SAMPLE_RATE
        out.update(primary=f"● Recording {secs:.0f} s",
                   secondary=f"Speak; {tap} again to stop and type")
    elif st.phase == "transcribing":
        out.update(badge="✎",
                   primary="Polishing…" if st.detail == "polishing" else "Transcribing…",
                   secondary="Typing into the focused window in a moment")
    elif st.phase == "paused":
        out.update(primary="Paused", secondary=f"Resume from the menu or {tap}")
    else:  # ready
        if eng.cfg.mode == "record":
            out.update(primary=f"Ready — {tap} to dictate", secondary=words + asr)
        else:
            live = "● Hearing speech" if eng.vad.in_speech else "Listening"
            out.update(primary=f"{live} — words appear as you speak",
                       secondary=words + asr)

    if eng.cfg.mode == "record":
        out["icon"] = "recording" if eng.recording else "idle"
        out["toggle"] = "Stop recording and type" if eng.recording else "Start recording"
        out["can_toggle"] = st.phase in ("ready", "recording")
    else:
        out["icon"] = ("paused" if eng.paused
                       else "recording" if eng.vad.in_speech else "idle")
        out["toggle"] = "Resume" if eng.paused else "Pause"
        out["can_toggle"] = True
    return out


# -----------------------------------------------------------------------------
# Menu bar
# -----------------------------------------------------------------------------


def run_menubar() -> int:
    import rumps

    engine_holder: dict = {"engine": None}

    class ParlandoApp(rumps.App):
        def __init__(self) -> None:
            super().__init__(
                "parlando",
                title=None,
                icon=ICONS["idle"],
                template=True,
                quit_button=None,
            )
            self._icon_state = "idle"
            self._ax_alerted = False
            self._guard = RelaunchGuard(app_bundle_path())
            self._guard.cleanup()
            # Status block: two text lines (disabled items) and an action
            # line that appears only when something needs the user.
            self.status_item = rumps.MenuItem("Starting up…")
            self.detail_item = rumps.MenuItem("")
            self.action_item = rumps.MenuItem("", callback=self.on_action)
            self._action_target = None
            self.toggle_item = rumps.MenuItem(
                "Start recording", callback=self.on_toggle
            )
            self.enter_item = rumps.MenuItem(
                "Press Enter after each utterance", callback=self.on_enter_mode
            )
            self.lang_items = {
                asr_name: rumps.MenuItem(label, callback=self.on_language)
                for label, asr_name in LANGUAGES.items()
            }
            self.menu = [
                self.status_item,
                self.detail_item,
                self.action_item,
                None,
                self.toggle_item,
                self.enter_item,
                {"Language": list(self.lang_items.values())},
                {"Vocabulary": [
                    rumps.MenuItem("Add Term…", callback=self.on_vocab_add),
                    rumps.MenuItem(
                        "Edit Vocabulary File…", callback=self.on_vocab_edit
                    ),
                ]},
                None,
                rumps.MenuItem("Open log file", callback=self.on_log),
                rumps.MenuItem("Quit", callback=self.on_quit),
            ]
            self._set_hidden(self.action_item, True)
            self._set_hidden(self.detail_item, True)
            # UI updates must happen on the main thread: polling engine state
            # from a main-loop timer is the thread-safe pattern.
            self._poll = rumps.Timer(self._refresh, 0.5)
            self._poll.start()

        @staticmethod
        def _set_hidden(item, hidden: bool) -> None:
            item._menuitem.setHidden_(hidden)

        @staticmethod
        def _set_title(item, title: str) -> None:
            if item.title != title:
                item.title = title

        def _set_icon(self, state: str) -> None:
            if state != self._icon_state:
                self._icon_state = state
                self.icon = ICONS[state]

        def _refresh(self, _timer) -> None:
            eng = engine_holder.get("engine")
            if eng is None:
                return
            if "accessibility" in eng.status.problems:
                self._guard.start()
            else:
                self._guard.stop()
            if eng.accessibility_missing and not self._ax_alerted:
                # No terminal to read the warning: say it once in a dialog.
                self._ax_alerted = True
                rumps.alert(
                    title="Parlando needs Accessibility access",
                    message=(
                        "Without it the hotkey cannot be heard and text cannot "
                        "be typed.\n\nSystem Settings > Privacy & Security > "
                        "Accessibility: enable Parlando (or the terminal you "
                        "started it from). Parlando picks it up by itself, "
                        "and reopens itself if macOS quits it when you flip "
                        "the switch."
                    ),
                )
            for lang, item in self.lang_items.items():
                item.state = int(eng.cfg.language == lang)

            view = describe_status(eng)
            if self.title != view["badge"]:
                self.title = view["badge"]
            self._set_icon(view["icon"])
            self._set_title(self.status_item, view["primary"])
            self._set_title(self.detail_item, view["secondary"])
            self._set_hidden(self.detail_item, not view["secondary"])
            action = view["action"]
            if action != self._action_target:
                self._action_target = action
                self._set_hidden(self.action_item, action is None)
                if action:
                    self._set_title(self.action_item, _PROBLEM_TEXT[action][2])
            self._set_title(self.toggle_item, view["toggle"])
            if bool(self.toggle_item.callback) != view["can_toggle"]:
                self.toggle_item.set_callback(self.on_toggle if view["can_toggle"] else None)

        def on_action(self, _item) -> None:
            pane = SETTINGS_PANES.get(self._action_target or "")
            if pane:
                subprocess.run(["open", pane], check=False)

        def on_toggle(self, _item) -> None:
            eng = engine_holder["engine"]
            if eng:
                eng.request_toggle()

        def on_enter_mode(self, item) -> None:
            eng = engine_holder["engine"]
            if eng:
                eng.cfg.send_enter = not eng.cfg.send_enter
                item.state = eng.cfg.send_enter

        def on_language(self, item) -> None:
            eng = engine_holder.get("engine")
            if not eng:
                return
            # Menu title -> ASR language tag; the model is multilingual, so
            # switching is instant with no model reload.
            for lang, mi in self.lang_items.items():
                if mi is item:
                    eng.cfg.language = lang
                    engine.LOGGER.info("language changed: %s", lang)
                    break

        def on_vocab_add(self, _item) -> None:
            # NOT rumps.Window: in an accessory (menu bar) app its modal can
            # open invisibly BEHIND other windows and freeze the main thread
            # (stuck "…" badge). The osascript dialog always comes frontmost.
            script = (
                'text returned of (display dialog '
                '"Term the ASR should spell exactly as written '
                '(e.g. MLX, PyPI, Wispr Flow):" '
                'default answer "" '
                'with title "parlando — add vocabulary term" '
                'buttons {"Cancel", "Add"} default button "Add")'
            )
            try:
                result = subprocess.run(
                    ["osascript", "-e", script],
                    capture_output=True,
                    text=True,
                    timeout=180,
                )
            except subprocess.TimeoutExpired:
                return
            if result.returncode != 0:
                return  # cancelled
            term = result.stdout.strip()
            if not term:
                return
            eng = engine_holder.get("engine")
            if eng is not None:
                # Active for the very next dictation; no restart needed.
                eng.add_vocab_term(term)

        def on_vocab_edit(self, _item) -> None:
            path = engine.VOCAB_FILE
            try:
                path.parent.mkdir(parents=True, exist_ok=True)
                if not path.exists():
                    path.write_text(
                        "# parlando vocabulary — one term per line.\n"
                        "# The ASR writes these exactly as spelled here.\n",
                        encoding="utf-8",
                    )
            except OSError:
                pass
            # -t: open in the default text editor. Saved edits are picked up
            # automatically at the next recording (mtime check).
            subprocess.run(["open", "-t", str(path)], check=False)

        def on_log(self, _item) -> None:
            subprocess.run(["open", str(engine.LOG_PATH)], check=False)

        def on_quit(self, _item) -> None:
            self._guard.stop()
            rumps.quit_application()

    app = ParlandoApp()

    def engine_thread() -> None:
        engine._setup_logging()
        eng = engine.DictationEngine(engine.Config())
        engine_holder["engine"] = eng
        try:
            asyncio.run(eng.run())
        except Exception:  # noqa: BLE001
            # rumps notifications need an app bundle; a log line is enough.
            engine.LOGGER.exception("engine crashed")
            print(
                f"[error] engine stopped — details: {engine.LOG_PATH}",
                file=sys.stderr,
            )

    threading.Thread(target=engine_thread, daemon=True).start()
    app.run()
    return 0


def main() -> int:
    if "--install-app" in sys.argv:
        return install_app()
    if "--uninstall-app" in sys.argv:
        return uninstall_app()
    if "--install-login" in sys.argv:
        return install_login()
    if "--uninstall-login" in sys.argv:
        return uninstall_login()
    return run_menubar()


if __name__ == "__main__":
    raise SystemExit(main())
