"""parlando menu bar app.

Runs the dictation engine in the background; the menu bar offers start/stop,
language switching, Enter mode and quit. No terminal window needed.

Usage:
    parlando                   # start in the menu bar (the default of `parlando`)
    parlando --install-app     # create ~/Applications/Parlando.app (recommended)
    parlando --uninstall-app
    parlando --install-login   # auto-start at login (opens Parlando.app)
    parlando --uninstall-login
    parlando-menubar           # same app; kept as an alias

Why an app bundle: macOS ties Microphone and Accessibility permissions to
the *responsible* application. Run from a terminal, that is Terminal/iTerm/
VS Code, which is confusing and breaks whenever you switch terminals.
`--install-app` writes a thin bundle (Info.plist, icon, a prebuilt Mach-O
stub and a launch script) that execs this package's Python; launched from Finder, Spotlight or the
LaunchAgent, permissions are then requested and stored as "Parlando".

Menu bar icon (template, adapts to light/dark): outline mic = ready,
filled mic = recording, slashed mic = paused; a small badge (ᵉⁿ / ᵗʳ)
appears when the language is not the default (Turkish). The global hotkey works too (default:
single tap of right Option).
"""

from __future__ import annotations

import asyncio
import os
import plistlib
import shutil
import subprocess
import sys
import threading
from pathlib import Path

from parlando import engine

BUNDLE_ID = "com.parlando.menubar"
APP_BUNDLE = Path.home() / "Applications" / "Parlando.app"
LAUNCH_AGENT = Path.home() / "Library" / "LaunchAgents" / f"{BUNDLE_ID}.plist"
APP_LOG = Path.home() / "Library" / "Logs" / "parlando-app.log"

LANGUAGES = {
    "Türkçe": "Turkish",
    "English": "English",
}
# Superscript badge shown next to the icon when the language is not the
# default (Config.language).
LANGUAGE_BADGES = {"Turkish": "ᵗʳ", "English": "ᵉⁿ"}

# Template icons (black + alpha): macOS recolors them to match the menu bar
# in light and dark mode. Regenerate with scripts/make_icons.py.
_ASSETS = Path(__file__).resolve().parent / "assets"
ICONS = {
    "idle": str(_ASSETS / "mic.png"),
    "recording": str(_ASSETS / "mic-recording.png"),
    "paused": str(_ASSETS / "mic-paused.png"),
}
APP_ICNS = _ASSETS / "Parlando.icns"
# Prebuilt Mach-O stub (scripts/launcher.c): macOS will not launch a bundle
# whose main executable is a script, so this binary execs launch.sh.
APP_LAUNCHER_BIN = _ASSETS / "parlando-launcher"


# -----------------------------------------------------------------------------
# App bundle (~/Applications/Parlando.app)
# -----------------------------------------------------------------------------

# launch.sh execs the interpreter that owns this package (uv tool or a
# venv). Using `python -m` rather than the console script keeps it valid
# across reinstalls. stdout/stderr go to a log: there is no terminal.
_LAUNCH_SH = """#!/bin/sh
# Parlando.app launch script, generated by `parlando-menubar --install-app`.
exec {python} -m parlando.menubar "$@" >>"$HOME/Library/Logs/parlando-app.log" 2>&1
"""


def bundle_plist() -> dict:
    # Deliberately no package version here: the bundle is only a launcher,
    # and ad-hoc signed bundles are identified by content hash in the
    # privacy database. A stable bundle keeps granted permissions valid
    # across `uv tool upgrade parlando`.
    return {
        "CFBundleName": "Parlando",
        "CFBundleDisplayName": "Parlando",
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": "parlando",
        "CFBundleIconFile": "Parlando",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": "1.0",
        "CFBundleVersion": "1",
        "CFBundleInfoDictionaryVersion": "6.0",
        "LSMinimumSystemVersion": "13.0",
        "LSUIElement": True,  # menu bar only: no Dock icon, no app switcher
        "NSHighResolutionCapable": True,
        "NSHumanReadableCopyright": "MIT License",
        "NSMicrophoneUsageDescription": (
            "Parlando listens to your voice to type what you say. "
            "Audio never leaves this Mac."
        ),
    }


def build_app_bundle(dest: Path, python: str | None = None, sign: bool = True) -> Path:
    """Write a minimal .app at `dest` (replacing any existing one)."""
    python = python or sys.executable
    contents = dest / "Contents"
    macos = contents / "MacOS"
    resources = contents / "Resources"
    if dest.exists():
        shutil.rmtree(dest)
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    with open(contents / "Info.plist", "wb") as fh:
        plistlib.dump(bundle_plist(), fh)
    exe = macos / "parlando"
    shutil.copyfile(APP_LAUNCHER_BIN, exe)
    exe.chmod(0o755)
    script = resources / "launch.sh"
    script.write_text(_LAUNCH_SH.format(python=_sh_quote(python)))
    script.chmod(0o755)
    shutil.copyfile(APP_ICNS, resources / "Parlando.icns")

    if sign:
        # Ad-hoc signature: no certificate needed. It gives the bundle a
        # stable identity for the privacy (TCC) database.
        subprocess.run(
            ["codesign", "--force", "--deep", "--sign", "-",
             "--identifier", BUNDLE_ID, str(dest)],
            check=True,
            capture_output=True,
        )
    return dest


def _sh_quote(path: str) -> str:
    return "'" + path.replace("'", "'\\''") + "'"


_LSREGISTER = (
    "/System/Library/Frameworks/CoreServices.framework/Frameworks/"
    "LaunchServices.framework/Support/lsregister"
)


def install_app() -> int:
    build_app_bundle(APP_BUNDLE)
    # Register with LaunchServices so Spotlight/Finder show the name and
    # icon immediately instead of after the next indexing pass.
    if os.path.exists(_LSREGISTER):
        subprocess.run([_LSREGISTER, "-f", str(APP_BUNDLE)], check=False, capture_output=True)
    print(
        f"Installed: {APP_BUNDLE}\n"
        "Open it from Finder or Spotlight (\"Parlando\"). macOS will ask for "
        "Microphone and Accessibility permissions in the name of Parlando; "
        "grant both, then quit and reopen the app once.\n"
        f"App output goes to {APP_LOG}"
    )
    return 0


def uninstall_app() -> int:
    if LAUNCH_AGENT.exists():
        uninstall_login()
    if APP_BUNDLE.exists():
        shutil.rmtree(APP_BUNDLE)
        print(f"Removed {APP_BUNDLE}")
    else:
        print("Not installed.")
    return 0


# -----------------------------------------------------------------------------
# Start at login (LaunchAgent)
# -----------------------------------------------------------------------------


def install_login() -> int:
    # Launch through the app bundle so permissions belong to "Parlando",
    # not to a bare python binary. Build it only if missing: rewriting a
    # bundle changes its hash and would invalidate granted permissions.
    if not APP_BUNDLE.exists():
        build_app_bundle(APP_BUNDLE)
        print(f"Created {APP_BUNDLE}")
    plist = {
        "Label": BUNDLE_ID,
        "ProgramArguments": ["/usr/bin/open", "-g", str(APP_BUNDLE)],
        "RunAtLoad": True,
        "KeepAlive": False,
        "StandardErrorPath": str(Path.home() / "Library/Logs/parlando-agent.log"),
    }
    LAUNCH_AGENT.parent.mkdir(parents=True, exist_ok=True)
    with open(LAUNCH_AGENT, "wb") as fh:
        plistlib.dump(plist, fh)
    subprocess.run(["launchctl", "unload", str(LAUNCH_AGENT)], capture_output=True)
    subprocess.run(["launchctl", "load", str(LAUNCH_AGENT)], check=False)
    print(f"Installed: {LAUNCH_AGENT}\nparlando will start at your next login.")
    return 0


def uninstall_login() -> int:
    subprocess.run(["launchctl", "unload", str(LAUNCH_AGENT)], capture_output=True)
    if LAUNCH_AGENT.exists():
        LAUNCH_AGENT.unlink()
        print("Uninstalled.")
    else:
        print("Not installed.")
    return 0


# -----------------------------------------------------------------------------
# Menu bar
# -----------------------------------------------------------------------------


def run_menubar() -> int:
    import rumps

    engine_holder: dict = {"engine": None}

    class ParlandoApp(rumps.App):
        def __init__(self) -> None:
            super().__init__(
                "parlando",
                title=None,
                icon=ICONS["idle"],
                template=True,
                quit_button=None,
            )
            self._icon_state = "idle"
            self._ax_alerted = False
            self.toggle_item = rumps.MenuItem(
                "Start recording", callback=self.on_toggle
            )
            self.enter_item = rumps.MenuItem(
                "Press Enter after each utterance", callback=self.on_enter_mode
            )
            self.lang_items = {
                asr_name: rumps.MenuItem(label, callback=self.on_language)
                for label, asr_name in LANGUAGES.items()
            }
            self.menu = [
                self.toggle_item,
                self.enter_item,
                {"Language": list(self.lang_items.values())},
                None,
                rumps.MenuItem("Open log file", callback=self.on_log),
                rumps.MenuItem("Quit", callback=self.on_quit),
            ]
            # UI updates must happen on the main thread: polling engine state
            # from a main-loop timer is the thread-safe pattern.
            self._poll = rumps.Timer(self._refresh, 0.5)
            self._poll.start()

        def _set_icon(self, state: str) -> None:
            if state != self._icon_state:
                self._icon_state = state
                self.icon = ICONS[state]

        def _refresh(self, _timer) -> None:
            eng = engine_holder.get("engine")
            if eng is None:
                return
            if eng.accessibility_missing and not self._ax_alerted:
                # No terminal to read the warning: say it once in a dialog.
                self._ax_alerted = True
                rumps.alert(
                    title="Parlando needs Accessibility access",
                    message=(
                        "Without it the hotkey cannot be heard and text cannot "
                        "be typed.\n\nSystem Settings > Privacy & Security > "
                        "Accessibility: enable Parlando (or the terminal you "
                        "started it from), then quit and reopen Parlando."
                    ),
                )
            for lang, item in self.lang_items.items():
                item.state = int(eng.cfg.language == lang)
            # Small text badge next to the icon for a non-default language.
            badge = (
                ""
                if eng.cfg.language == engine.Config.language
                else LANGUAGE_BADGES.get(eng.cfg.language, "")
            )
            if self.title != badge:
                self.title = badge
            if eng.cfg.mode == "record":
                if eng.recording:
                    self._set_icon("recording")
                    self.toggle_item.title = "Stop recording and type"
                else:
                    self._set_icon("idle")
                    self.toggle_item.title = "Start recording"
                return
            if eng.paused:
                self._set_icon("paused")
                self.toggle_item.title = "Resume"
            elif eng.vad.in_speech:
                self._set_icon("recording")
                self.toggle_item.title = "Pause"
            else:
                self._set_icon("idle")
                self.toggle_item.title = "Pause"

        def on_toggle(self, _item) -> None:
            eng = engine_holder["engine"]
            if eng:
                eng.request_toggle()

        def on_enter_mode(self, item) -> None:
            eng = engine_holder["engine"]
            if eng:
                eng.cfg.send_enter = not eng.cfg.send_enter
                item.state = eng.cfg.send_enter

        def on_language(self, item) -> None:
            eng = engine_holder.get("engine")
            if not eng:
                return
            # Menu title -> ASR language tag; the model is multilingual, so
            # switching is instant with no model reload.
            for lang, mi in self.lang_items.items():
                if mi is item:
                    eng.cfg.language = lang
                    engine.LOGGER.info("language changed: %s", lang)
                    break

        def on_log(self, _item) -> None:
            subprocess.run(["open", str(engine.LOG_PATH)], check=False)

        def on_quit(self, _item) -> None:
            rumps.quit_application()

    app = ParlandoApp()

    def engine_thread() -> None:
        engine._setup_logging()
        eng = engine.DictationEngine(engine.Config())
        engine_holder["engine"] = eng
        try:
            asyncio.run(eng.run())
        except Exception:  # noqa: BLE001
            # rumps notifications need an app bundle; a log line is enough.
            engine.LOGGER.exception("engine crashed")
            print(
                f"[error] engine stopped — details: {engine.LOG_PATH}",
                file=sys.stderr,
            )

    threading.Thread(target=engine_thread, daemon=True).start()
    app.run()
    return 0


def main() -> int:
    if "--install-app" in sys.argv:
        return install_app()
    if "--uninstall-app" in sys.argv:
        return uninstall_app()
    if "--install-login" in sys.argv:
        return install_login()
    if "--uninstall-login" in sys.argv:
        return uninstall_login()
    return run_menubar()


if __name__ == "__main__":
    raise SystemExit(main())
